### ISSUE TITLE
Erro no nest-api ao conectar no Kafka

### ISSUE THREAD

**Issue by Twsouza** [codeedu/imersao-fsfc2#1]
Olá.

Estou com um problema para iniciar a api e conectar no Kafka. Fiz o clone do projeto no meu computador (Ubuntu 20.04) e quando dou um up no nest-api (com o apache kafka já rodando), gera erro para mim:

```
app_1            | (node:41) UnhandledPromiseRejectionWarning: KafkaJSNonRetriableError
app_1            |   Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 127.0.0.1:9094
```

Eu adicionei o endereço ao hosts:

```
127.0.0.1       localhost
127.0.0.1       host.docker.internal
```

**Comment by argentinaluiz** [comment]
Olá @Twsouza ,

O Apache Kafka está rodando normalmente pelo Docker? Consegue acessar a interface da Confluent?

**Comment by victorhgadioli** [comment]
Estou tendo o mesmo problema. E não, não consigo acessa a interface da Confluent. Estou utilizando um clone do repositório do curso.

**Comment by Twsouza** [comment]
Boa tarde @argentinaluiz,

Consigo acessar o apacha kafka pelo control-center, consigo visualizar os tópicos `route.new-direction` e `route.new-position`. Inclusive já rodei o `system prune -a` só para ter certeza e continua o mesmo erro no nest-api.

@victorhgadioli tenta acessar o control-center, adiciona o código abaixo no docker-compose do apache-kafka

```

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
```

E acessa o localhost:9021
